version: '3.8'

# ===================================================================
# DOCKER COMPOSE PARA DESPLIEGUE DISTRIBUIDO MULTI-HOST
# ===================================================================
# Este archivo permite ejecutar el sistema distribuido usando
# Docker Swarm o en múltiples hosts con Docker

services:
  # OpenFire XMPP Server (Host Central)
  openfire:
    image: sameersbn/openfire:3.10.3-19
    container_name: openfire_central
    restart: always
    ports:
      - "9090:9090"   # Admin console
      - "5222:5222"   # XMPP port
      - "7777:7777"   # HTTP bind
    environment:
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
    volumes:
      - openfire_data:/var/lib/openfire
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.role == manager  # Ejecutar solo en nodo manager

  # Coordinator Service (Host Central)
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: taxi_coordinator
    restart: always
    depends_on:
      - openfire
    environment:
      - HOST_TYPE=coordinator
      - HOST_ID=coordinator_main
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - MAX_AGENTS_PER_HOST=100
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Taxi Host Service (Host Remoto 1)
  taxi-host-1:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: taxi_host_1
    restart: always
    depends_on:
      - coordinator
    environment:
      - HOST_TYPE=taxi_host
      - HOST_ID=taxi_host_1
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - COORDINATOR_HOST=coordinator
      - MAX_TAXIS_PER_HOST=50
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.labels.host_type == taxi
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Taxi Host Service (Host Remoto 2)
  taxi-host-2:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: taxi_host_2
    restart: always
    depends_on:
      - coordinator
    environment:
      - HOST_TYPE=taxi_host
      - HOST_ID=taxi_host_2
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - COORDINATOR_HOST=coordinator
      - MAX_TAXIS_PER_HOST=50
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.labels.host_type == taxi
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Passenger Host Service (Host Remoto 3)
  passenger-host-1:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: passenger_host_1
    restart: always
    depends_on:
      - coordinator
    environment:
      - HOST_TYPE=passenger_host
      - HOST_ID=passenger_host_1
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - COORDINATOR_HOST=coordinator
      - MAX_PASSENGERS_PER_HOST=100
      - PASSENGER_SPAWN_RATE=0.2
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.labels.host_type == passenger
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Passenger Host Service (Host Remoto 4)
  passenger-host-2:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: passenger_host_2
    restart: always
    depends_on:
      - coordinator
    environment:
      - HOST_TYPE=passenger_host
      - HOST_ID=passenger_host_2
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - COORDINATOR_HOST=coordinator
      - MAX_PASSENGERS_PER_HOST=100
      - PASSENGER_SPAWN_RATE=0.3
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.labels.host_type == passenger
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Web Monitor (Optional)
  web-monitor:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: taxi_web_monitor
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - coordinator
    environment:
      - COORDINATOR_HOST=coordinator
      - OPENFIRE_HOST=openfire
    networks:
      - taxi_network
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  taxi_network:
    driver: overlay
    attachable: true

volumes:
  openfire_data:
    driver: local
