version: '3.8'

# ===================================================================
# DOCKER COMPOSE PARA DESPLIEGUE DISTRIBUIDO FINAL
# ===================================================================
# Cumple requisito académico: Al menos 2 hosts remotos

networks:
  taxi_distributed:
    external: true

volumes:
  openfire_data:

services:
  # OpenFire XMPP Server (Host Central)
  openfire:
    image: sameersbn/openfire:3.10.3-19
    container_name: openfire_distributed
    restart: always
    ports:
      - "9090:9090"   # Admin console
      - "5222:5222"   # XMPP port
      - "7777:7777"   # HTTP bind
    environment:
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
    volumes:
      - openfire_data:/var/lib/openfire
    networks:
      - taxi_distributed
    deploy:
      placement:
        constraints:
          - node.role == manager

  # Host Central - Coordinador del sistema
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: coordinator
    restart: always
    depends_on:
      - openfire
    environment:
      - HOST_TYPE=coordinator
      - HOST_ID=coordinator
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - MAX_AGENTS_PER_HOST=50
    networks:
      - taxi_distributed
    deploy:
      placement:
        constraints:
          - node.labels.host_type == coordinator
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Host Remoto 1 - Agentes Taxi
  taxi-host-1:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: taxi_host_1
    restart: always
    depends_on:
      - openfire
    environment:
      - HOST_TYPE=taxi_host
      - HOST_ID=taxi_host_1
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - MAX_AGENTS_PER_HOST=100
    networks:
      - taxi_distributed
    deploy:
      placement:
        constraints:
          - node.labels.host_type == taxi_host
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Host Remoto 2 - Agentes Pasajero
  passenger-host-1:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: passenger_host_1
    restart: always
    depends_on:
      - openfire
    environment:
      - HOST_TYPE=passenger_host
      - HOST_ID=passenger_host_1
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - MAX_AGENTS_PER_HOST=150
    networks:
      - taxi_distributed
    deploy:
      placement:
        constraints:
          - node.labels.host_type == passenger_host
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Host Remoto 3 - Agentes Taxi Adicional (Opcional)
  taxi-host-2:
    build:
      context: .
      dockerfile: Dockerfile.distributed
    container_name: taxi_host_2
    restart: always
    depends_on:
      - openfire
    environment:
      - HOST_TYPE=taxi_host
      - HOST_ID=taxi_host_2
      - OPENFIRE_HOST=openfire
      - OPENFIRE_DOMAIN=taxisystem.local
      - OPENFIRE_ADMIN_USER=admin
      - OPENFIRE_ADMIN_PASSWORD=123
      - OPENFIRE_SECRET_KEY=jNw5zFIsgCfnk75M
      - MAX_AGENTS_PER_HOST=100
    networks:
      - taxi_distributed
    deploy:
      placement:
        constraints:
          - node.labels.host_type == taxi_host
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

