services:
  env_agent:
    build:
      context: ./env_agent
      dockerfile: ../Dockerfile.agent
    container_name: environmentAgent
    environment:
      - XMPP_SERVER=openfire
    command: python environment_agent_ws.py
    networks:
      - agents-net

  tower_agent:
    build:
      context: ./tower_agent
      dockerfile: ../Dockerfile.agent
    container_name: towerAgent1
    depends_on:
      - env_agent
    environment:
      - XMPP_SERVER=openfire
    command: python tower_agent.py
    networks:
      - agents-net

networks:
  agents-net:
    driver: bridge
