FROM python:3.11-slim

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    gcc build-essential libffi-dev libssl-dev && \
    pip install spade websockets

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos del agente (serán añadidos por cada servicio)
COPY . /app

CMD ["python", "main.py"]
